### ISSUE TITLE
Ukol c.1

### ISSUE THREAD

**Issue by MikaCK** [MikaCK/python-course-2022#1]
https://github.com/MikaCK/python-course-2022/blob/main/baliky.py

Test - odovzdanie ukolu - aj ked este nedokonceny

**Comment by MikaCK** [comment]
Prepac Odra, som commital change do master branch...tu je ukol dokonceny

https://github.com/MikaCK/python-course-2022/blob/main/homework1.py

https://github.com/MikaCK/python-course-2022/blob/main/baliky.py

https://github.com/MikaCK/python-course-2022/blob/main/homework1_bonus.py

**Comment by pixelneo** [comment]
Baliky jsou spravne. 
Slo by to lehce zkratit: misto `if baliky[kod_baliku] == True:` lze napsat `if baliky[kod_baliku]:`, ale to je detail.

**Comment by pixelneo** [comment]
https://github.com/MikaCK/python-course-2022/blob/main/homework1.py take spravne :-) 

Tip: misto `if found_region == False:` by slo napsat `if not found_region:`, kde operator `not` je negace (je-li tedy `found_region` `True` pak `not found_region` je `False`.

**Comment by pixelneo** [comment]
Bonus taky ok. Pekne!

Mej se.
