### ISSUE TITLE
Ukol slovniky/cyckly

### ISSUE THREAD

**Issue by MikaCK** [MikaCK/python-course-2022#2]
https://github.com/MikaCK/python-course-2022/blob/main/homework1.py

https://github.com/MikaCK/python-course-2022/blob/main/baliky.py

https://github.com/MikaCK/python-course-2022/blob/main/homework1_bonus.py

**Comment by pixelneo** [comment]
Spravne. (uz jsem odpovedel v https://github.com/MikaCK/python-course-2022/issues/1)
