### ISSUE TITLE
Ukol 3 & 4

### ISSUE THREAD

**Issue by MikaCK** [MikaCK/python-course-2022#3]
https://github.com/MikaCK/python-course-2022/blob/main/evidence_aut.py

https://github.com/MikaCK/python-course-2022/blob/main/sms_brana.py

Odovzdavam ukol 3 a 4. 'Sms brana' je aj s bonusom, ale 'Evidence aut' je bez bonusu. Nestihla som. 
Pisala som vsetko v anglictine, dufam, ze to nevadi. 

Vdaka

**Comment by pixelneo** [comment]
Ahoj, 3. spravne. A dokonce bych rekl, ze velmi pekne! :-)

**Comment by pixelneo** [comment]
4 taky perfektni!
