### ISSUE TITLE
Ukol-05: Streamovací služba

### ISSUE THREAD

**Issue by MikaCK** [MikaCK/python-course-2022#4]
https://github.com/MikaCK/python-course-2022/blob/main/stream_sluzba.py

V mojom ukole ma Třída Serial atributy n_episodes (pocet epizod) a len_episodes (delke epizody). Ale skusila som to urobit tak, ze kazda epizoda ma trochu inu dlzku, takze si potom vyberieme cislo epizody, a zistime aku ma dlzku konkretna epizoda. 

Uloha je zatial bez bonusu.

**Comment by pixelneo** [comment]
Ahoj, pekne! (opet :-))
Muzes zkusit ten bonus, jestli se ti bude chtit, ale body uz mas :-)
