### ISSUE TITLE
Ukol c.6 a c.7

### ISSUE THREAD

**Issue by MikaCK** [MikaCK/python-course-2022#5]
https://github.com/MikaCK/python-course-2022/blob/main/posta.py

https://github.com/MikaCK/python-course-2022/blob/main/pujcovna_aut.py

Ukol.c7 - posta - nasla som 12 adries, nie 17, lebo som si nevedela poradit s regularnym prikazom, aby pokryl obe adresy:

460 15 LIBEREC 15
512 11 VYSOKÉ NAD JIZEROU. 

Tak som tu prvu odstranila. Urcite by som sa este pohrala este s upravou v oboch pripadoch, myslim, ze by sa dal kod napisat aj krajsie. Kvoli kratkosti casu posielam to, co mam. Este jeden ukol poslem v priebehu par dni, aby som mala 8 odovzdanych, kvoli certifikatu :)

Vdaka

Michaela

**Comment by pixelneo** [comment]
Ahoj, pujcovna aut ok.
Posta, skoro si to mela: `\d{3} \d{2} \w+(?: \w+)*(?: [0-9]+)?` (chybejici zavorka na konci)
Takze oba ok.

Mej se. Ondra
